### ISSUE TITLE
이동 구현

### ISSUE THREAD

**Issue by kdy1** [skku-comit/Abalone#1]

**Comment by DropFL** [comment]
- [x] HexGrid에서 가능한 이동 방향을 나타내는 enum같은 객체들을 만든다. (편의상 `Direction`으로 명명)
- [ ] `Collection<Ball>`과 `Direction`을 인자로 받아 움직임을 구현하는 `Move` 메서드를 만든다.
- [ ] `Collection<Ball>`을 인자로 받아 주어진 공들을 움직이는 것이 룰에 어긋나는지 판별하는 `IsValid` 메서드를 만든다.
- [ ] `Collection<Ball>`과 `Direction`을 인자로 받아 주어진 공들을 해당 방향으로 움직이는 것이 룰에 어긋나는지 판별하는 `IsValid` 메서드를 만든다.  (overloading)

more?

**Comment by kdy1** [comment]
@skku-comit/csharp-project 누가 할지 정하자
