### ISSUE TITLE
드래그 처리

### ISSUE THREAD

**Issue by kdy1** [skku-comit/Abalone#2]
현재는 마우스 클릭만 처리하는데, 마우스로 드래그하거나 손가락으로 드래그하는 걸 처리해줘야 함

**Comment by DropFL** [comment]
드래그를 처리하는 방식이 2개가 있는데

하나는 [이런 식으로](https://answers.unity.com/questions/433757/using-rectcontains-to-check-against-world-coordina.html) 드래그해서 만들어진 사각형 영역에 있는 공을 모두 선택하는 방법이 있고 (스타 생각하면 될듯)

하나는 마우스가 드래그하는 동안 지나가는 모든 공을 선택하는 방법이 있음

어떤거?

**Comment by kdy1** [comment]
@DropFL 선택하기 위해 드래그하는 게 아니고, 공을 이동시키는 방향을 정하기 위한 드래그야

**Comment by DropFL** [comment]
@kdy1 그럼 그냥
